name: Build PR documentation

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.number }}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/doc-builder'
          path: doc-builder

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/optimum'
          path: optimum

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/optimum-habana'
          path: optimum-habana

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set env
        run: |
          echo "WRITE=$(echo 'ghp_'$(wget -qO- lysand.re/doc-build-dev)'bm')" >> $GITHUB_ENV

      - name: Setup environment
        run: |
          pip uninstall -y doc-builder
          cd doc-builder
          git pull origin main
          pip install -e .
          pip install black
          cd ..

      - name: Make Habana documentation
        env:
          NODE_OPTIONS: --max-old-space-size=6656
        run: |
          cd optimum-habana
          git fetch origin
          git checkout documentation
          make doc BUILD_DIR=habana-doc-build
          sudo mv habana-doc-build ../optimum
          cd ..

      - name: Combine subpackage documentation
        env:
          NODE_OPTIONS: --max-old-space-size=6656
        run: |
          cd optimum
          make doc BUILD_DIR=base-doc-build VERSION=pr_$PR_NUMBER
          python docs/combine_doc.py
          sudo mv base-doc-build ../
          cd ..

      - name: Push to repositories
        run: |
          cd base-doc-build
          doc-builder push optimum --doc_build_repo_id "huggingface/doc-build-dev" --token ${{ env.WRITE }} --commit_msg "Updated with commit $COMMIT_SHA See: https://github.com/huggingface/optimum/commit/$COMMIT_SHA" --n_retries 5
        shell: bash

      - name: Find doc comment
        if: github.event.action == 'reopened'
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: HuggingFaceDocBuilderDev

      - name: Add doc comment
        uses: thollander/actions-comment-pull-request@v1
        if: github.event.action == 'opened'

        with:
          message: 'The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum/pr_${{ env.PR_NUMBER }}). All of your documentation changes will be reflected on that endpoint.'
          GITHUB_TOKEN: ${{ env.WRITE }}

      - name: Update doc comment if necessary
        if: github.event.action == 'reopened'
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          token: ${{ env.WRITE }}
          edit-mode: replace
          body: |
            The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum/pr_${{ env.PR_NUMBER }}). All of your documentation changes will be reflected on that endpoint.
