name: Build main documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/doc-builder'
          path: doc-builder

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/doc-build'
          path: doc-build
          token: ${{ secrets.HUGGINGFACE_PUSH }}

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/optimum'
          path: optimum

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/optimum-habana'
          path: optimum-habana

      - name: Set env variables
        run: |
          echo "write_token=$(echo 'ghp_'$(wget -qO- lysand.re/doc-build-dev)'bm')" >> $GITHUB_ENV
          cd optimum
          version=`echo "$(grep '^__version__ =' optimum/version.py | cut -d '=' -f 2- | xargs)"`

          if [[ $version == *.dev0 ]]
          then
            echo "VERSION=main" >> $GITHUB_ENV
          else
            echo "VERSION=v$version" >> $GITHUB_ENV
          fi

          cd ..

      - name: Setup environment
        run: |
          pip uninstall -y doc-builder
          cd doc-builder
          git pull origin main
          pip install .
          pip install black
          cd ..

      - name: Create build directory
        run: |
          mkdir build_dir
          mkdir build_dir/optimum
          cd build_dir/optimum
          wget https://raw.githubusercontent.com/huggingface/doc-build/main/optimum/_versions.yml

      - name: Make Habana documentation
        env:
          NODE_OPTIONS: --max-old-space-size=6656
        run: |
          cd optimum-habana
          git fetch origin
          git checkout documentation
          make doc BUILD_DIR=habana-doc-build
          sudo mv habana-doc-build ../optimum
          cd ..

      - name: Make Optimum documentation
        env:
          NODE_OPTIONS: --max-old-space-size=6656
        run: |
          cd optimum
          make doc BUILD_DIR=optimum-doc-build VERSION=${{ env.VERSION }}
          cd ..

      - name: Combine subpackage documentation
        env:
          NODE_OPTIONS: --max-old-space-size=6656
        run: |
          cd optimum
          sudo python docs/combine_docs.py --subpackages habana --version ${{ env.VERSION }}
          sudo mv optimum-doc-build ../
          cd ..

      - name: Push to repositories
        run: |
          cd build_dir
          doc-builder push optimum --doc_build_repo_id "huggingface/doc-build" --token ${{ env.write_token }} --commit_msg "Updated with commit ${{ github.sha }} See: https://github.com/huggingface/optimum/commit/${{ github.sha }}" --n_retries 5
        shell: bash
